version: 1
formatters:
  simple_format:
    format: '%(asctime)s - %(levelname)s - %(threadName)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple_format
    stream: ext://sys.stdout
root:
  level: WARN
  handlers: [console]
  propagate: yes
loggers:
  recursiveai.findflow:
    level: DEBUG
    propagate: yes
disable_existing_loggers: false
